export enum CategoryEnum {
  NEW_RELEASES = "NEW_RELEASES",
  TOP_RATED = "TOP_RATED",
  COMING_SOON = "COMING_SOON",
  MORE_FREE_ITEMS = 'MORE_FREE_ITEMS',
  TRENDING = 'TRENDING',
  POPULAR = 'MOST POPULAR',
  SALE_SPOTLIGHT = 'MAY_THE_4TH_SALE_SPOTLIGHT'
}

